import * as assert from 'assert';
import { categorizeDefinitions, assembleSketch, SketchSections } from '../codegen/targets/arduino/cpp/assemble';
import { SecondaryFileEntryPointError } from '../codegen/generationErrors';

suite('categorizeDefinitions', () => {
    test('splits definitions by key prefix, preserving order', () => {
        const s = categorizeDefinitions({
            'import_a': '#include <Wire.h>',
            'import_b': '#include <Modulino.h>',
            'decl_a': 'ModulinoThermo _thermo;',
            'func_blink': 'void blink() {}',
            'setup_a': '_thermo.begin();',
        });
        assert.deepStrictEqual(s.includes, ['#include <Wire.h>', '#include <Modulino.h>']);
        assert.deepStrictEqual(s.declarations, ['ModulinoThermo _thermo;']);
        assert.deepStrictEqual(s.helpers, ['void blink() {}']);
        assert.deepStrictEqual(s.setup, ['_thermo.begin();']);
    });

    test('ignores unknown prefixes (e.g. cleanup_) and empty values', () => {
        const s = categorizeDefinitions({ 'cleanup_x': 'foo();', 'setup_e': '', 'decl_x': 'int n;' });
        assert.deepStrictEqual(s.setup, []);
        assert.deepStrictEqual(s.declarations, ['int n;']);
    });
});

suite('assembleSketch', () => {
    const empty: SketchSections = { includes: [], declarations: [], helpers: [], setup: [] };

    test('empty workspace yields empty setup() and loop() stubs', () => {
        const out = assembleSketch(empty, '');
        assert.ok(out.includes('void setup() {\n}'), out);
        assert.ok(out.includes('void loop() {\n}'), out);
        assert.ok(out.startsWith('// This code has been automatically generated by Maker Block Studio.'), out);
    });

    test('omits the timestamp line when no generatedAt is given', () => {
        const out = assembleSketch(empty, '');
        assert.ok(!out.includes('// Last generated:'), out);
    });

    test('stamps the generation timestamp in the header when provided', () => {
        const out = assembleSketch(empty, '', '2026-06-14 12:34:56 UTC');
        assert.ok(out.includes('// Last generated: 2026-06-14 12:34:56 UTC'), out);
        // timestamp belongs to the header block, before any code section
        assert.ok(out.indexOf('// Last generated:') < out.indexOf('void setup()'), out);
    });

    test('places setup sections inside setup(), indented', () => {
        const out = assembleSketch({ ...empty, setup: ['Wire1.begin();', '_thermo.begin();'] }, '');
        assert.ok(out.includes('void setup() {\n  Wire1.begin();\n\n  _thermo.begin();\n}') === false);
        // setup lines are joined with '\n' and indented:
        assert.ok(out.includes('void setup() {\n  Wire1.begin();\n  _thermo.begin();\n}'), out);
    });

    test('wraps top-level statements into loop(), indented', () => {
        const out = assembleSketch(empty, 'digitalWrite(13, HIGH);\ndelay(100);');
        assert.ok(out.includes('void loop() {\n  digitalWrite(13, HIGH);\n  delay(100);\n}'), out);
    });

    test('orders sections: includes, declarations, helpers, setup, loop', () => {
        const out = assembleSketch(
            {
                includes: ['#include <Arduino.h>'],
                declarations: ['int counter;'],
                helpers: ['void helper() {}'],
                setup: ['Serial.begin(9600);'],
            },
            'counter++;'
        );
        const iInc = out.indexOf('#include <Arduino.h>');
        const iDecl = out.indexOf('int counter;');
        const iHelp = out.indexOf('void helper()');
        const iSetup = out.indexOf('void setup()');
        const iLoop = out.indexOf('void loop()');
        assert.ok(iInc < iDecl && iDecl < iHelp && iHelp < iSetup && iSetup < iLoop, out);
    });

    suite('isSecondary', () => {
        test('omits setup()/loop() entirely when the workspace has no entry-point content', () => {
            const out = assembleSketch(
                { includes: ['#include <Wire.h>'], declarations: [], helpers: ['void blink() {}'], setup: [] },
                '',
                undefined,
                true
            );
            assert.ok(!out.includes('void setup()'), out);
            assert.ok(!out.includes('void loop()'), out);
            assert.ok(out.includes('#include <Wire.h>'), out);
            assert.ok(out.includes('void blink() {}'), out);
        });

        test('throws SecondaryFileEntryPointError when a Setup block has content', () => {
            assert.throws(
                () => assembleSketch({ ...empty, setup: ['Wire1.begin();'] }, '', undefined, true),
                SecondaryFileEntryPointError
            );
        });

        test('throws SecondaryFileEntryPointError when there are top-level (loop) statements', () => {
            assert.throws(
                () => assembleSketch(empty, 'digitalWrite(13, HIGH);', undefined, true),
                SecondaryFileEntryPointError
            );
        });

        test('does not throw for a non-secondary file with the same content', () => {
            assert.doesNotThrow(() => assembleSketch({ ...empty, setup: ['x();'] }, 'y();', undefined, false));
        });
    });
});
