/**
 * Assembles a complete Arduino C++ sketch from the generator's `definitions_`
 * map plus the loop body (the concatenation of top-level workspace statements).
 *
 * Mirrors the Arduino App Lab model: there are no explicit setup/loop scaffold
 * blocks — every top-level statement becomes the `loop()` body, while the
 * `codegen.setup` sections collected from blocks become the `setup()` body.
 *
 * This module is intentionally pure (no Blockly/VS Code deps) so it is unit
 * testable and shared between the webview generator and tests.
 */

export interface SketchSections {
    includes: string[];
    declarations: string[];
    prototypes: string[];
    helpers: string[];
    setup: string[];
}

function buildHeader(generatedAt?: string): string {
    const lines = [
        '// This code has been automatically generated by Maker Block Studio.',
        '// Changes are overwritten whenever the blocks are edited.',
    ];
    if (generatedAt) {lines.push(`// Last generated: ${generatedAt}`);}
    return lines.join('\n');
}

const INDENT = '  ';

/**
 * Split a generator `definitions_` map into ordered sketch sections by key prefix.
 * Prefixes are written by the template engine: import_/include_, decl_, proto_, func_, setup_.
 * Insertion order is preserved (keys are non-numeric). Unknown prefixes (e.g.
 * cleanup_) are ignored for C++.
 */
export function categorizeDefinitions(definitions: Record<string, string>): SketchSections {
    const sections: SketchSections = { includes: [], declarations: [], prototypes: [], helpers: [], setup: [] };
    for (const [key, value] of Object.entries(definitions)) {
        if (!value) {continue;}
        if (key.startsWith('import_') || key.startsWith('include_')) {sections.includes.push(value);}
        else if (key.startsWith('decl_')) {sections.declarations.push(value);}
        else if (key.startsWith('proto_')) {sections.prototypes.push(value);}
        else if (key.startsWith('func_')) {sections.helpers.push(value);}
        else if (key.startsWith('setup_')) {sections.setup.push(value);}
    }
    return sections;
}

function indentBlock(code: string): string {
    return code
        .split('\n')
        .map(line => (line.length ? INDENT + line : line))
        .join('\n');
}

function wrapFunction(name: string, body: string): string {
    const trimmed = body.replace(/\n+$/, '');
    return trimmed ? `${name} {\n${indentBlock(trimmed)}\n}` : `${name} {\n}`;
}

/**
 * @param isSecondary When true, this file is a companion to the project's main
 * sketch: it must not define `setup()`/`loop()` (the main file already does,
 * and PlatformIO/arduino-cli compile every source file together — two
 * definitions of either name is a link error). Only includes, declarations,
 * and helper functions are emitted. The webview keeps `sections.setup` and
 * `loopBody` empty in practice (it disables any Setup/top-level block while
 * the workspace is marked secondary), but this function drops them silently
 * either way rather than assuming that invariant holds.
 */
export function assembleSketch(
    sections: SketchSections,
    loopBody: string,
    generatedAt?: string,
    isSecondary = false
): string {
    const parts: string[] = [buildHeader(generatedAt)];

    if (sections.includes.length) {parts.push("// Includes\n" + sections.includes.join('\n') + "\n// End of includes");}
    if (sections.declarations.length) {parts.push("// Global declarations\n" + sections.declarations.join('\n') + "\n// End of global declarations");}
    if (sections.prototypes.length) {parts.push("// Function prototypes\n" + sections.prototypes.join('\n') + "\n// End of function prototypes");}
    if (sections.helpers.length) {parts.push("// Helper functions\n" + sections.helpers.join('\n') + "\n// End of helper functions");}

    if (!isSecondary) {
        parts.push("// Initialization code\n" + wrapFunction('void setup()', sections.setup.join('\n')) + "\n// End of initialization code");
        parts.push("// Forever running code\n" + wrapFunction('void loop()', loopBody ?? '') + "\n// End of forever running code");
    }

    return parts.join('\n\n') + '\n';
}
